# Generated by Django 4.2.5 on 2023-09-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCitasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='direccion',
            field=models.CharField(max_length=80),
        ),
    ]
